use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StartupStartResult {
    pub project_slug: String,
    pub project_root: String,
    pub runtime_home: String,
    pub cwd: String,
    pub team_id: String,
    pub manager_name: String,
    pub manager_role: String,
    pub manager_session_name: String,
    pub manager_agent_session_id: String,
    pub manager_seed_turn_id: Option<String>,
    pub session_dir: String,
    pub planned_worker_count: usize,
    pub worker_names: Vec<String>,
    pub launch_status: String,
    pub session_lifecycle: String,
    pub bootstrap_prompt_status: String,
    pub skill_install_status: String,
    pub skill_path: String,
    pub cli_path: String,
    pub agent_session_status: String,
    pub control_handoff_status: String,
    pub tui_resume_command: String,
    pub tui_resume_arg_count: usize,
    pub resource_lease_id: String,
    pub resource_snapshot_id: String,
    pub tmux_session_observed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StartupWorkerResult {
    pub project_slug: String,
    pub project_root: String,
    pub runtime_home: String,
    pub cwd: String,
    pub team_id: String,
    pub agent_name: String,
    pub agent_role: String,
    pub team_role: String,
    pub session_name: String,
    pub agent_session_id: String,
    pub seed_turn_id: Option<String>,
    pub session_dir: String,
    pub launch_status: String,
    pub session_lifecycle: String,
    pub bootstrap_prompt_status: String,
    pub skill_install_status: String,
    pub skill_path: String,
    pub cli_path: String,
    pub agent_session_status: String,
    pub control_handoff_status: String,
    pub tui_resume_command: String,
    pub tui_resume_arg_count: usize,
    pub resource_lease_id: String,
    pub resource_snapshot_id: String,
    pub tmux_session_observed: bool,
}
